// Writes src/admin/config.yml (the Decap CMS setup) from the content files.
// Run after adding pages or text keys:  npm run cms-config
import fs from "node:fs";
import path from "node:path";

const PAGES = {
  common: "Header, footer & shared", ui: "Buttons, cookie prompt & hours wording", home: "Home", explore: "Explore",
  g_lifelike: "Gallery: Lifelike Scenes & Statues", g_legacy: "Gallery: Legacy Architecture",
  g_scripture: "Gallery: Walking into Scripture", g_tapestry: "Gallery: A Living Tapestry",
  ajanta: "Exhibit: Ajanta Caves", x_ranikivav: "Exhibit: Rani-ki-Vav", x_konark: "Exhibit: Konark Wheel",
  x_haveli: "Exhibit: Traditional Haveli", x_dholavira: "Exhibit: Dholavira Bazaar",
  timeline: "Timeline", visit: "Plan your visit", learn: "Learn", support: "Support", notfound: "Page not found",
};
const LANGS = { en: "English", gu: "Gujarati (ગુજરાતી)", hi: "Hindi (हिन्दी)" };
const q = (s) => JSON.stringify(s); // YAML accepts JSON strings
const plain = (s) => String(s).replace(/<[^>]+>/g, "").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();
const short = (s, n) => (s.length > n ? s.slice(0, n - 1) + "…" : s);

const time = (name, label) => `      - { name: ${name}, label: ${q(label)}, widget: datetime, date_format: false, time_format: "HH:mm", format: "HH:mm", picker_utc: false, required: false }`;
const day = (d) => `              - name: ${d}
                label: ${q(d[0].toUpperCase() + d.slice(1))}
                widget: object
                collapsed: true
                fields:
                  - { name: closed, label: "Closed all day", widget: boolean, default: false }
${time("opens", "Opens").replace(/^ {6}/, "                  ")}
${time("closes", "Closes").replace(/^ {6}/, "                  ")}`;

let y = `# Generated by scripts/cms-config.js — edit that script, not this file.
backend:
  name: github
  repo: OWNER/REPOSITORY   # set this when the site has a GitHub repository
  branch: main
# "npm run cms" (decap-server) lets you use the admin locally without logging in
local_backend: true
media_folder: src/images
public_folder: /images
locale: en

collections:
  - name: status
    label: "Opening hours & notices"
    description: "Regular hours, special dates (holidays, closures, special hours) and notices shown at the top of every page."
    editor: { preview: false }
    files:
      - name: site-status
        label: "Opening hours & notices"
        file: src/data/site-status.json
        fields:
          - { name: sample_hours, label: "These are sample hours (highlight them in yellow on the site)", widget: boolean, default: false }
          - { name: timezone, label: "Time zone", widget: hidden, default: "America/New_York" }
          - name: regular_hours
            label: "Regular weekly hours"
            widget: object
            fields:
${["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].map(day).join("\n")}
          - name: special_dates
            label: "Special dates"
            label_singular: "special date"
            hint: "Holidays, closures or different hours on a particular day. These override the regular hours."
            widget: list
            summary: "{{fields.date}} {{fields.note_en}}"
            fields:
              - { name: date, label: "Date", widget: datetime, date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
              - { name: closed, label: "Closed all day", widget: boolean, default: true }
${time("opens", "Opens (if open)").replace(/^ {6}/, "              ")}
${time("closes", "Closes (if open)").replace(/^ {6}/, "              ")}
              - { name: note_en, label: "Note (English)", widget: string, required: false, hint: "e.g. Closed for Thanksgiving" }
              - { name: note_gu, label: "Note (Gujarati)", widget: string, required: false }
              - { name: note_hi, label: "Note (Hindi)", widget: string, required: false }
          - name: notices
            label: "Notices"
            label_singular: "notice"
            hint: "A bar at the top of every page. Switch it on, and optionally set when it starts and ends."
            widget: list
            summary: "{{fields.type}}: {{fields.message_en}}"
            fields:
              - { name: id, label: "Short name (no spaces)", widget: string, hint: "e.g. snow-closure-jan-12. Used to remember who closed the notice." }
              - { name: active, label: "Show this notice", widget: boolean, default: true }
              - { name: type, label: "Type", widget: select, options: [{ label: "Information", value: info }, { label: "Warning", value: warning }, { label: "Closure", value: closure }], default: info }
              - { name: starts, label: "Show from", widget: datetime, format: "YYYY-MM-DDTHH:mm", date_format: "YYYY-MM-DD", time_format: "HH:mm", picker_utc: false, required: false, hint: "Museum time (New York). Leave empty to show straight away." }
              - { name: ends, label: "Show until", widget: datetime, format: "YYYY-MM-DDTHH:mm", date_format: "YYYY-MM-DD", time_format: "HH:mm", picker_utc: false, required: false, hint: "Leave empty to show until you switch it off." }
              - { name: message_en, label: "Message (English)", widget: text }
              - { name: message_gu, label: "Message (Gujarati)", widget: text, required: false }
              - { name: message_hi, label: "Message (Hindi)", widget: text, required: false }
              - { name: link_url, label: "Link", widget: string, required: false, hint: "e.g. /visit/ or a full web address" }
              - { name: link_label_en, label: "Link text (English)", widget: string, required: false }
              - { name: link_label_gu, label: "Link text (Gujarati)", widget: string, required: false }
              - { name: link_label_hi, label: "Link text (Hindi)", widget: string, required: false }
`;

const en = {};
for (const f of fs.readdirSync("src/content/en")) en[f.replace(".json", "")] = JSON.parse(fs.readFileSync(path.join("src/content/en", f), "utf8"));
const order = Object.keys(PAGES).filter((p) => en[p]).concat(Object.keys(en).filter((p) => !PAGES[p]));

const eraFields = `                  - { name: dates, label: "Dates", widget: string }
                  - { name: name, label: "Name", widget: string }
                  - { name: summary, label: "Summary", widget: text }
                  - { name: keys, label: "Key names & works", widget: string }
                  - { name: num, label: "Number", widget: string }
                  - name: see
                    label: "See it in the museum"
                    widget: list
                    fields:
                      - { name: title, label: "Title", widget: string }
                      - { name: kind, label: "Kind", widget: string }
                      - { name: where, label: "Where", widget: string }
                      - { name: img, label: "Image", widget: string, required: false }
                      - { name: hasImg, label: "Has image", widget: boolean, required: false }
                      - { name: href, label: "Link", widget: string }`;

for (const [lang, langName] of Object.entries(LANGS)) {
  y += `
  - name: text_${lang}
    label: "Site text — ${langName}"
    description: "${lang === "en" ? "The English wording of every page." : "Leave a field empty to show the English text there until it is translated."}"
    editor: { preview: false }
    files:
`;
  for (const page of order) {
    y += `      - name: ${page}
        label: ${q(PAGES[page] || page)}
        file: src/content/${lang}/${page}.json
        fields:
`;
    for (const [key, val] of Object.entries(en[page])) {
      if (Array.isArray(val)) {
        y += `          - name: ${key}
            label: "Timeline eras"
            widget: list
            required: false
            ${lang === "en" ? "" : 'hint: "Leave empty to use the English eras."\n            '}summary: "{{fields.num}} {{fields.name}}"
            fields:
${eraFields}
`;
        continue;
      }
      const p = plain(val);
      const label = short(p || key, 70);
      const widget = p.length > 90 || /<[^>]+>/.test(val) ? "text" : "string";
      const hints = [];
      if (lang !== "en") hints.push("English: " + short(p, 300));
      if (/<[^>]+>/.test(val)) hints.push("Keep any <tags> as they are; they make links and highlights.");
      y += `          - { name: ${key}, label: ${q(label)}, widget: ${widget}, required: ${lang === "en"}${hints.length ? ", hint: " + q(hints.join("  ")) : ""} }\n`;
    }
  }
}
fs.writeFileSync("src/admin/config.yml", y);
console.log("wrote src/admin/config.yml");
